export const TOUR_DETAILS = [
	{
		title: "Port Blair To Havelock",
		description:
			"Havelock Island is exotic tropical island nestled 52 km away north east of port blair City . It is the most sought after tourist destination in Andaman islands. Ferry/cruise services are the only way to reach Havelock since there is no road linking Port Blair to Havelock for land transportation. Private Ferry and Luxury cruises operate daily from Port Blair to Havelock scheduled morning and afternoon trips from Haddo Jetty in Port Blair. Tourists can book for morning or afternoon ferry/cruise trip from Port Blair to Havelock Island as per their flight arrival. Ferry Harbor is about 3-5 km from the airport. It is always good to keep at least 2- 3 hours for Ferry transfer from Havelock to Port Blair and from Port Blair to Havelock. It is safe to book ferry for next day if you flight arrival is afternoon since the last port blair Havelock ferry trip is 12:20 am and those who arrive morning before 11 :00 am can book same day port to Havelock ferry ticket for afternoon trips. Ferry Route option in andamans and Most Popular Tourist Circuit. Port Blair to Havelock and returnPort To havelock and transfer to Port Via Neil route from Havelock. Private Luxury ferries operate daily from Port Blair morning and afternoon trips from Haddo Jetty in Port Blair. All ferry Start and end their day trip from port Blair and end at port blair by evening sunset.",
		requirements: "Since Andamans is cluster of island to reach most of the tourist places you will have to book ferry or boat which are the only viable means of transport and these are scheduled with limited availability and capacity especially during season. There fore it is important to book you ferry and boat tickets in advance so that you don't end you paying for hotels cancellation and rescheduling which may happen due to unavailability of ferrybooking while trying upon reaching here and waste time rather than enjoying your holiday. We issue instant ferry ticket automatically confirmed from respective ferry company online reservation system therefore its as good as book and without any need reconfirmation from either us or ferry companies. We do not charge any thing apart from the ferry companies ticket cost to our customer . for booking worth 5000 and more we avail many discount coupon on activities and boat tickets. For Group (greater than 26 no of person) we offer discounts which can be availed by email / call with our customer service executives. Its is advisable to keep a day in port blair while entry and exit specially during rainy reason or at least 2 hrs between flight arrival and ferry departure. You should reach ferry hourbour 1 hr before schdueded departure time. Always make a tour plan and book your ticket to match your timings. If you need any information to plan your tour or need information regarding route and logistic you may feel free to call our helpline for free consulting as we are local company with info and access that would help you to make best tour plan and ferry booking.",
		
	}
];
