import Head from "next/head";
import Image from "next/image";

import { Select, DatePicker, Button, Space, Card } from "antd";
const { Meta } = Card;
const { RangePicker } = DatePicker;

import styles from "@styles/Home.module.css";
import Navbar from "@components/appComponents/Navbar";
import Faq from "@components/pageComponents/Faq";
import { faqs, placeOptions } from "src/constants/constants";

export default function Home() {
	const gridStyle = {
		width: "25%",
		textAlign: "center"
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Navbar />
				<div className={styles.header}>
					<div>
						<Image
							alt="home_image"
							src="/assets/home.jpg"
							className={styles.header_image}
							layout="fill"
						/>
					</div>
					<div className={styles.header_details}>
						<h1>Your Travel Partner</h1>
						<div>
							<Space>
								<Select
									defaultValue="India"
									style={{ width: 120 }}
									options={placeOptions}
								/>
								<Select
									defaultValue="India"
									style={{ width: 120 }}
									options={placeOptions}
								/>
								<RangePicker showTime />
								<Button type="primary">Search</Button>
							</Space>
						</div>
					</div>
				</div>
				<div className={styles.wrapper}>
					<h1>Travel guides</h1>
					<div className={styles.card_container}>
						<Card
							hoverable
							style={{
								width: 250,
								marginBlock: "1rem"
							}}
							cover={
								<img
									alt="example"
									src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
									style={{ height: 150, objectFit: "cover" }}
								/>
							}
						>
							<Meta title="Europe" />
						</Card>
						<Card
							hoverable
							style={{
								width: 250,
								marginBlock: "1rem"
							}}
							cover={
								<img
									alt="example"
									src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
									style={{ height: 150, objectFit: "cover" }}
								/>
							}
						>
							<Meta title="Europe" />
						</Card>
						<Card
							hoverable
							style={{
								width: 250,
								marginBlock: "1rem"
							}}
							cover={
								<img
									alt="example"
									src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
									style={{ height: 150, objectFit: "cover" }}
								/>
							}
						>
							<Meta title="Europe" />
						</Card>
						<Card
							hoverable
							style={{
								width: 250,
								marginBlock: "1rem"
							}}
							cover={
								<img
									alt="example"
									src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
									style={{ height: 150, objectFit: "cover" }}
								/>
							}
						>
							<Meta title="Europe" />
						</Card>
						<Card
							hoverable
							style={{
								width: 250,
								marginBlock: "1rem"
							}}
							cover={
								<img
									alt="example"
									src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
									style={{ height: 150, objectFit: "cover" }}
								/>
							}
						>
							<Meta title="Europe" />
						</Card>
					</div>
				</div>
				<div className={styles.wrapper}>
					<h1>Popular Routes</h1>
					<Card title="Thailand" style={{ marginBottom: ".5rem" }}>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
					</Card>
					<Card title="India">
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
						<Card.Grid style={gridStyle}>Budapest &#8594; Bangkok</Card.Grid>
					</Card>
				</div>
				<div className={styles.wrapper}>
					<h1>Frequently Asked Questions</h1>
					<Faq faqs={faqs} />
				</div>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
